# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ae77806e099dad1873bd56147928ba137b836f9c2d0138c61bbd394d045764712ca019d3cdb846b986d4bbc3162bfeefb5a9b0edba40546692c9e8456d4912d

test:
  secret_key_base: f333a9db0df6e2f63a367a99311dc8d126f1eac79e337b72ae6e7dec568703893a8f3c0dac947edc56f015c8de595813b471ffbcbf595f62e51bec20669b0b1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
